export const FETCH_QUIZES_START = 'FETCH-QUIZES-START';
export const FETCH_QUIZES_SUCCESS = 'FETCH-QUIZES-SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH-QUIZES-ERROR';
export const FETCH_QUIZ_BY_ID_SUCCESS = 'FETCH-QUIZ-BY-ID-SUCCESS';

export const ANSWER_CLICK = 'ANSWER-CLICK';
export const RETRY_HANDLER = 'RETRY-HANDLER';
export const SET_ANSWER_STATE_AND_RESULTS = 'SET-ANSWER-STATE-AND-RESULTS';
export const SET_IS_FINISHED = 'SET-IS-FINISHED';
export const NEXT_QUESTION = 'NEXT-QUESTION';
export const TO_QUIZ_BEGINING = 'TO-QUIZ-BEGINNING';

export const ADD_QUESTION = 'ADD-QUESTION';

export const AUTH_SUCCESS = 'AUTH-SUCCESS';
export const AUTH_LOGOUT = 'AUTH-LOGOUT';

export const CHANGE_ANSWERS_COUNT = 'CHANGE-ANSWERS-COUNT';




